from __future__ import annotations

from enum import Enum

class PointsType(Enum):
    NoPointsType = ...
    GaussGaussLegendre = ...
    GaussRadauMLegendre = ...
    GaussRadauPLegendre = ...
    GaussLobattoLegendre = ...
    GaussGaussChebyshev = ...
    GaussRadauMChebyshev = ...
    GaussRadauPChebyshev = ...
    GaussLobattoChebyshev = ...
    GaussRadauMAlpha0Beta1 = ...
    GaussRadauMAlpha0Beta2 = ...
    GaussRadauMAlpha1Beta0 = ...
    GaussRadauMAlpha2Beta0 = ...
    GaussKronrodLegendre = ...
    GaussRadauKronrodMLegendre = ...
    GaussRadauKronrodMAlpha1Beta0 = ...
    GaussLobattoKronrodLegendre = ...
    PolyEvenlySpaced = ...
    FourierEvenlySpaced = ...
    FourierSingleModeSpaced = ...
    BoundaryLayerPoints = ...
    BoundaryLayerPointsRev = ...
    NodalTriElec = ...
    NodalTriFekete = ...
    NodalTriEvenlySpaced = ...
    NodalTetEvenlySpaced = ...
    NodalTetElec = ...
    NodalPrismEvenlySpaced = ...
    NodalPrismElec = ...
    NodalTriSPI = ...
    NodalTetSPI = ...
    NodalPrismSPI = ...
    NodalQuadElec = ...
    NodalHexElec = ...

class ShapeType(Enum):
    NoGeomShapeType = ...
    Point = ...
    Segment = ...
    Triangle = ...
    Quadrilateral = ...
    Tetrahedron = ...
    Pyramid = ...
    Prism = ...
    Hexahedron = ...

class SessionReader:
    @staticmethod
    def CreateInstance(ns: list[str]) -> SessionReader: ...
