[tool.mypy]
python_version = "3.10"
warn_return_any = true
warn_unused_configs = true
mypy_path = ["./typings"]
modules = ["example_mesh", "example_conformal"]
packages = ["neso_fame", "tests"]

[[tool.mypy.overrides]]
module = ["scipy.*"]
ignore_missing_imports = true

[tool.isort]
profile = "black"

[tool.coverage.run]
source = ["neso_fame/", ]
