name: Docs
on: 
  push:
    branches:
      - main
    tags:
      - v*
jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: cmacmackin/nekpy:latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3
      - name: Update PATH
        run: echo "/opt/view/bin" >> $GITHUB_PATH
      - name: Cache pip-installed packages
        uses: actions/cache@v3
        with:
          path: |
            /usr/local/bin/python3.10/dist-packages/
            ~/.cache/sphinx_immaterial/
          key: ${{ runner.os }}-${{ hashFiles('setup.py', 'requirements-dev.txt') }}
      - name: Install dependencies
        run: |
          python3 -m pip install --upgrade pip
          python3 -m pip install .
          python3 -m pip install -r requirements-dev.txt
          python3 -m pip install ghp-import # only required by this yaml for publishing the docs 
      - name: Build Website
        working-directory: ./docs/
        run: |
          make html
      - name: Setup Pages
        uses: actions/configure-pages@v3
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v1
        with:
          path: './docs/build/html/'

  deploy:
    needs: build
    permissions:
      pages: write
      id-token: write
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v2
